FROM tiangolo/uwsgi-nginx-flask:python3.6
ADD /requirements.txt requirements.txt
RUN pip install -r requirements.txt
RUN pip install git+https://github.com/photon-team/photon.git

ADD ./app /app

WORKDIR /
ENV PYTHONPATH = /

ENV STATIC_URL /main/static
# Absolute path in where the static files wil be
ENV STATIC_PATH /app/main/static


