name: PHOTONAI release deployment on PyPI

on:
  release:
    types: [published]

jobs:
  deploy:
    name: Build and publish to PyPI
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Set up Python 3.10.8
      uses: actions/setup-python@v4
      with:
        python-version: 3.10.8
    - name: Install pypa/build
      run: pip install build pbr wheel
    - name: Build a binary wheel and a source tarball
      run: python -m build -n --sdist --wheel --outdir dist/ .
    - name: Publish distribution to Test PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        user: __token__
        password: ${{ secrets.PYPI_API_TOKEN }}
